name: Release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"

      - name: Check version consistency
        run: |
          [[ "$(uv version --short)" == "$(git describe --tags)" ]]

      - name: Build project
        run: uv build

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    needs:
      - release
    permissions:
      id-token: write

    environment:
      name: PyPI
      url: https://pypi.org/project/acrm/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
